# Config file for automatic testing at travis-ci.org

language: python

python:
  - "current"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
